# Generated by Django 5.1.7 on 2025-04-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0002_purchase_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
