# Generated by Django 5.1.7 on 2025-04-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0004_cartitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productsbought',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
